#!/bin/bash
# Author: @FershoUno <https://github.com/FershoUno>

if [ "$(id -u)" -ne 0 ]; then
  echo "This script must be run as root."
  exit 1
fi

NAME="go"
ARCH="amd64"

rm -rf *.deb *.tar.gz ${NAME}*${ARCH}* "${NAME}" 2>/dev/null

URL=$(curl -s https://go.dev/dl/ | grep -oP '<a class="download downloadBox" href="\K(/dl/go[0-9.]+\.linux-amd64\.tar\.gz)' | sed 's|^|https://go.dev|')
wget -q --show-progress $URL

GO_TARGZ=$(basename "$URL")
tar -xzvf "$GO_TARGZ" -C .

VERSION=$(cat $NAME/VERSION | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')
DIR_PACKAGE="${NAME}_${VERSION}_${ARCH}"

mkdir -p "$DIR_PACKAGE/DEBIAN"
mkdir -p "$DIR_PACKAGE/usr/local"
mkdir -p "$DIR_PACKAGE/usr/bin"

cp -r "$NAME" "$DIR_PACKAGE/usr/local/"

GO_SIZE=$(du -ks --exclude=DEBIAN "$DIR_PACKAGE/" | awk '{print $1}')

cp control postinst prerm "$DIR_PACKAGE/DEBIAN/"

chmod 755 "$DIR_PACKAGE/DEBIAN/"{postinst,prerm}
chown -R root:root "$DIR_PACKAGE"

sed -i "s/CHANGE_VERSION/$VERSION/g" "$DIR_PACKAGE/DEBIAN/control"
sed -i "s/CHANGE_SIZE/$GO_SIZE/g" "$DIR_PACKAGE/DEBIAN/control"

dpkg-deb --build "$DIR_PACKAGE"
